/* CLASS 04 — source-of-truth configuration. No visible restaurant copy should live only in HTML. */
window.RestaurantDefaults={
  id:'restaurant-class4',schemaVersion:4,status:'draft',
  brand:{name:'LÚMINA',logoText:'LÚMINA',accent:'#d8ff4f',ink:'#080807',paper:'#ece6da',fontDisplay:'Italiana',fontBody:'DM Sans'},
  header:{links:[['Signature','#signature'],['Story','#story'],['Experience','#experience'],['Visit','#visit']],studioLabel:'Studio',reserveLabel:'Reservar'},
  hero:{kicker:'Alicante · Mediterranean dining',line1:'LÚMINA',line2:'after dark.',body:'Producto mediterráneo, fuego y precisión. Una carta que no se desplaza: orbita.',cta:'Descubrir el menú',stamp:'ORBITAL MENU · CLASS 04 ·',scroll:'SCROLL TO ENTER'},
  philosophy:{index:'01 / Philosophy',title:'La cocina entra en escena como un objeto de deseo, no como una lista.',body1:'Hemos diseñado cada plato bajo el mismo contrato fotográfico: encuadre, distancia, vajilla, fondo y luz. Esa disciplina hace posible la ilusión de volumen sin recurrir a 3D real.',body2:'El movimiento añade jerarquía; la fotografía aporta credibilidad. El resultado debe sentirse físico aunque todo siga siendo HTML, CSS, imágenes y GSAP.'},
  orbital:{index:'02 / Signature plates',kicker:'Drag · wheel · swipe · arrows',title:'The Orbital Menu',explore:'Explore dish'},
  origin:{index:'03 / Origin',title:'Before the plate, there is a place.',body:'La procedencia también forma parte de la interfaz. Ingrediente, productor y técnica aparecen como información de valor, no como letra pequeña.',caption:'Santa Pola · 07:20'},
  atmosphere:{index:'04 / Atmosphere',title:'Dinner becomes memory.',caption:'Dining room · Alicante',body:'Materia, temperatura, luz y sonido se diseñan con la misma intención que el plato.',cta:'Reserve your table →'},
  chef:{index:'05 / Chef',title:'Precision without noise.',quote:'“La técnica desaparece cuando el plato parece inevitable.”',badges:['Seasonal menu','Local producers','Fire-led kitchen']},
  visit:{kicker:'Alicante · Tue — Sat',title:'Take your seat.',cta:'Reservar mesa',addressLabel:'Address',address:'Muelle 08 · Alicante',serviceLabel:'Service',service:'19:30 — 00:30',contactLabel:'Contact',contact:'hello@lumina.demo',bookingUrl:'#'},
  footer:{left:'LÚMINA',center:'Class 05 · Motion Direction Premium',right:'Educational prototype'},
  motion:{
    orbitalStyle:'elegant',
    text:{hero:'cinematic',philosophy:'line',origin:'soft',atmosphere:'editorial',chef:'mask',visit:'rise'},
    media:{hero:'cinematic',origin:'parallax',atmosphere:'slowZoom',chef:'parallax'}
  },
  media:{
    hero:{type:'image',url:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104220_2a0413f3-7a7a-45a4-9fc3-1d63d737b488.png',fit:'cover',position:'50% 50%'},
    origin:{type:'image',url:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104220_5e88ce28-a269-420c-ac0f-fbaf6f0c7573.png',fit:'cover',position:'50% 50%'},
    atmosphere:{type:'image',url:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104220_2a0413f3-7a7a-45a4-9fc3-1d63d737b488.png',fit:'cover',position:'50% 50%'},
    chef:{type:'image',url:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104220_7aca7ce4-b18c-49b5-a54c-c64cae3aefbc.png',fit:'cover',position:'50% 50%'}
  },
  dishes:[
    {id:'dish-01',name:'Wild Red Prawn',meta:'Santa Pola · Fire · Citrus',short:'Red prawn, smoked almond, citrus beurre blanc and sea fennel.',price:'€28',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104106_bdf81ca0-1bf9-428a-86f9-97a68aed9cfb.png',ingredients:'Red prawn · smoked almond · citrus · sea fennel',origin:'Lonja de Santa Pola · Alicante',technique:'Olive wood charcoal · 38 seconds',pairing:'Moscatel seco · Alicante DOP',note:'Heat, iodine and citrus. Nothing else should get in the way.',allergens:'Shellfish · nuts',enabled:true},
    {id:'dish-02',name:'Bluefin / Blood Orange',meta:'Mediterranean · Raw · Ponzu',short:'Bluefin tuna, blood orange, caper leaf and black olive dust.',price:'€31',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104106_0787565e-8cf4-4fd3-86c2-0583aa9eaece.png',ingredients:'Bluefin tuna · blood orange · ponzu · caper leaf',origin:'Western Mediterranean',technique:'Hand-cut · cold dressed',pairing:'Brut nature rosé',note:'Acid first, then fat, then the sea.',allergens:'Fish · soy',enabled:true},
    {id:'dish-03',name:'Charred Artichoke',meta:'Vega Baja · Smoke · Hazelnut',short:'Caramelised artichoke, smoked yolk, parsley oil and toasted hazelnut.',price:'€22',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104106_106d173c-2fe5-4763-bccc-59ecfe401244.png',ingredients:'Artichoke · egg yolk · hazelnut · parsley oil',origin:'Vega Baja · Alicante',technique:'Ember-roasted · glazed',pairing:'Fondillón-inspired vermouth',note:'Vegetal bitterness deserves the same ceremony as seafood.',allergens:'Egg · nuts',enabled:true},
    {id:'dish-04',name:'Wild Sea Bass',meta:'Calpe · Saffron · Fennel',short:'Crisp-skinned sea bass, saffron sauce, leek and translucent fennel.',price:'€34',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104106_5aa3ae73-18a3-40e5-a05d-6c99799facb3.png',ingredients:'Sea bass · saffron · leek · fennel',origin:'Calpe coast · Alicante',technique:'Plancha · skin-side crisp',pairing:'Marina Alta white',note:'Crisp skin, soft centre, saffron held just below perfume.',allergens:'Fish · dairy',enabled:true},
    {id:'dish-05',name:'Iberian Presa',meta:'Dehesa · Ember · PX',short:'Iberian presa, roasted aubergine, Pedro Ximénez and spring onion.',price:'€36',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104106_901a0cde-ba99-48f4-a012-68bae6baf49f.png',ingredients:'Iberian pork · aubergine · PX · spring onion',origin:'Extremadura · Spain',technique:'Hard sear · ember rest',pairing:'Monastrell · Alicante DOP',note:'Smoke should frame the meat, never cover it.',allergens:'Sulphites',enabled:true},
    {id:'dish-06',name:'Burnt Honey Citrus',meta:'Alicante · Honey · Verbena',short:'Burnt-honey ice cream, citrus, olive-oil sponge and almond praline.',price:'€16',image:'https://d8j0ntlcm91z4.cloudfront.net/user_32Z72jiRnAYwuEpbVNGYFa3wWSz/hf_20260824_104106_1e54d625-3cab-4d8a-be7d-87b1d92c824b.png',ingredients:'Burnt honey · citrus · olive oil · almond',origin:'Alicante citrus & local honey',technique:'Churned · candied · aerated',pairing:'Late-harvest Moscatel',note:'Dessert with enough bitterness to keep the night awake.',allergens:'Dairy · egg · nuts',enabled:true}
  ]
};